### PR TITLE
Fix signing when input private key length is not 2048 bits

### LINKED ISSUE #9: RSA signature size isn't fixed
Your code is hardcoding RSA signature size as 256 bytes. Based on that you seem to be using a 2048 bit key - signature length is actually equal to key length. With a 4096 bit key it will be 512 bytes.

### PR DESCRIPTION
**Pull request by robertknight**
The output signature size depends upon the input key size, so will be
512 bytes rather than 256 if a 4096-bit key is used for example.

Calculate the signature size by signing dummy data rather than assuming
a fixed size.

Fixes #9

### CODE REVIEW

File: src/lib.ts [hunk 1]
```diff
@@ -110,6 +110,19 @@ function parseXML(content: string) {
...
+  * Determine the length of signature that will be generated when signing with
+  * the given private key using the SHA1 digest algorithm.
+  */
+function signatureLength(privateKey: string) {
+  // determine signature size by signing some dummy data
+  let signer = createSign('SHA1');
+  signer.update('dummy data');
+  let signature: Buffer = <any>signer.sign(privateKey,
+    undefined /* return a Buffer */);
+  return signature.length;
```
Comment (palant) [inline src/lib.ts]: Personally, I would rather reuse code. So rename this function into `sign(privateKey, data)` that will return the signature and do `sign(key, '').length` to calculate signature size (note that an empty string will do here because what's actually being signed is the SHA1 digest and that one has a constant size). You could then call `heapWriter.write(sign(key, compressedTOC))` when you need the actual signature.

File: src/lib.ts [hunk 2]
```diff
@@ -536,7 +545,7 @@ export class XarArchive {
         extractCertSection(this.signatureResources.cert),
         ...this.signatureResources.additionalCerts.map(extractCertSection)
       ];
-      let signatureSize = RSA_SIGNATURE_SIZE;
+      let signatureSize = signatureLength(this.signatureResources.privateKey);
```
Comment (palant) [inline src/lib.ts]: This might be premature optimization but signing is a non-trivial operation - can't you calculate signature size only once, e.g. when the private key is assigned?

**Comment by jhg-tgu** [comment]
Exists some due date about when will be this done? @robertknight

**Comment by robertknight** [comment]
Thank-you for the feedback @palant , I've implemented the suggestions.
